version: '3.3'

services:
  db:
    container_name: meritorder_postgres
    restart: unless-stopped
    image: postgres:13.0-alpine
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    env_file:
      - .env.dev

  django:
    container_name: meritorder_django
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8888
    ports:
      - 8888:8888
    volumes:
      - ./backend:/code
    env_file:
      - .env.dev
    depends_on:
      - db

volumes:
  postgres_vol:
